version: 2
tags: [git]
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable

instructions:
  Build:
    - !include "{{qt/qtbridge-java}}/build_java.yaml"
  Test:
    - !include "{{qt/qtbase}}/run_license_check.yaml"
